### ISSUE TITLE
当在tab切换进行显示隐藏，表单自适应布局出现问题

### ISSUE THREAD

**Issue by agrass-GitHub** [dream2023/vue-ele-form#11]

**Comment by dream2023** [comment]
什么问题？

**Comment by agrass-GitHub** [comment]
问题场景是：for 循环一个 ele-form，用 tab 切换进行显示隐藏，如果不指定 labelPosition，和 span 属性，表单不会根据自适应规则自适应。

![image](https://user-images.githubusercontent.com/30621542/64243549-20fcc500-cf3a-11e9-8a09-3a61db0cd1d4.png)

**Comment by agrass-GitHub** [comment]
还有个建议想法：目前响应式规则是按照窗口的宽度进行调整，如果可以根据 ele-form 的div 容器宽度来自适应 layout 和 label-position 会不会更好呢。

**Comment by dream2023** [comment]
ele-form就是根据div 容器进行设置的

**Comment by dream2023** [comment]
> 还有个建议想法：目前响应式规则是按照窗口的宽度进行调整，如果可以根据 ele-form 的div 容器宽度来自适应 layout 和 label-position 会不会更好呢。

ele-form就是根据 div 容器进行设置的

**Comment by dream2023** [comment]
> for 循环一个 ele-form，用 tab 切换进行显示隐藏，如果不指定 labelPosition，和 span 属性，表单不会根据自适应规则自适应。如果有个方法可以主动调用就可以了。

有代码吗？

**Comment by dream2023** [comment]
已确定为bug， 现在正在修复

**Comment by dream2023** [comment]
已修复
