### ISSUE TITLE
date 类型组件设置 attrs valuFormat，无法正常工作

### ISSUE THREAD

**Issue by agrass-GitHub** [dream2023/vue-ele-form#12]
![image](https://user-images.githubusercontent.com/30621542/63990827-fc5ab480-cb17-11e9-96c1-c92c3fe60839.png)

![image](https://user-images.githubusercontent.com/30621542/63990677-78083180-cb17-11e9-81d4-3daf5f58b3ab.png)

**Comment by dream2023** [comment]
`valueFormat` 不是 `valuFormat`，你少打了个`e`

**Comment by agrass-GitHub** [comment]
> `valueFormat`不是`valuFormat`，你少打了个`e`
![image](https://user-images.githubusercontent.com/30621542/64125353-3cea5480-cddc-11e9-8218-8234853dd39f.png)

![image](https://user-images.githubusercontent.com/30621542/64125231-e846d980-cddb-11e9-877e-8265bac8c65a.png)

感谢回复，截图的确是我打错了，但是我拼写正确再次测试，还是会出现同样的结果呢，版本也是最新的版本。

**Comment by dream2023** [comment]
呃。。。还不是`valueFormat` 是 `valueFormatter`，而且类型为`Function`

参考文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/iw5dzf#4fzKL
