### ISSUE TITLE
表单提交时的错误提示框的问题！

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#13]
当表单提交时，如果有错误，会显示一个错误提示框！这个框有两个问题。
1. 如果没有注册 全局方法 $notify ， 后台开发人员工具会提示错误警告，前台看不到提示弹出框。采用按需加载element组件时， 需要手动注册
Vue.component(Notification)
Vue.prototype.$notify = Notification;
2， 弹出的对话框，标题title固定死了 '表单填写错误'，还是中文的!  建议去掉，或者可以在外面自定义设置。
3. 建议vue-ele-form固定的地方都搞成自定义，不太方便的话，内部使用的话，请用英文！
我的QQ 2810923 微信 13986759836

参考代码如下：
EleForm.vue
    // 显示错误
    showError (messageArr) {
      if (messageArr.length) {
        const h = this.$createElement
        messageArr = messageArr.map(msg => {
          return h('div', { style: { marginBottom: '8px' } }, msg)
        })
        this.$notify.error({
          title: '表单填写错误',
          message: h('div', { style: { minWidth: '300px', marginTop: '12px' } }, messageArr)
        })
      }
    },

**Comment by dream2023** [comment]
国际化正准备做，在1.0的时候 会正式发布

**Comment by dream2023** [comment]
你说的按需加载的问题，我会考虑一下的，可以兼容处理

**Comment by dream2023** [comment]
国际化已完成：https://www.yuque.com/chaojie-vjiel/vbwzgu/gh11wg
