### ISSUE TITLE
参数 formBtns 自定义按钮数组参数无效！

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#14]
我设置了表单的自定义按钮数组，但是无效。查看代码，是EleForm.vue 里的初始化错误，btns.concat(customBtns) 会连接两个数组，并返回新的数组，但是原数组btns数据是不会变得。请修正下！

以下是参考代码
      // 自定义按钮
      if (this.formBtns) {
        const customBtns = this.formBtns.map((btn) => ({
          attrs: {
            type: btn.type,
            size: formBtnSize
          },
          text: btn.text,
          click: btn.click
        }))
        btns.concat(customBtns)
      }

**Comment by dream2023** [comment]
已修复，感谢建议！！
