### ISSUE TITLE
form-desc 属性接收一个对象，没办法对表单项进行排序？

### ISSUE THREAD

**Issue by agrass-GitHub** [dream2023/vue-ele-form#15]
form-desc 属性接收一个对象，没办法对表单项进行排序，像 field 为 1， 会自动变成第一位， 请问以后考虑添加一个排序属性吗？

![image](https://user-images.githubusercontent.com/30621542/64243964-d465b980-cf3a-11e9-8a0c-814e00f2f386.png)

**Comment by dream2023** [comment]
加到是可以加，但是我不明白在什么场景下会需要根据字段排序呢，对象设置顺序就可以达到排序的效果啊

**Comment by xem1987** [comment]
@dream2023 作者你好，我也在近期开发一个类似的功能组件，并配有后台，一点建议提一下。
排序问题是存在的，你当前的设计表单元素是使用对象，但是js的对象遍历是不确定的，如果从后台传表单配置，很可能导致表单显示顺序的不确定性
建议改进方案
1. 对field配置从kv模式，改为数组，将key以一个属性单独放置在field内部，这样兼容性可能会有影响
1. 保持现在的kv模式，在field属性中增加显示次序标识，这样兼容性和功能性均得到保障

**Comment by dream2023** [comment]
> 排序问题是存在的，你当前的设计表单元素是使用对象，但是js的对象遍历是不确定的，如果从后台传表单配置，很可能导致表单显示顺序的不确定性

1、因为存在大量的更新和查找操作，如果用数组，每次都需要遍历；
2、目前还没遇到过顺序不对的情况，如果你遇到了，可以给我说一下

**Comment by xem1987** [comment]
> > 排序问题是存在的，你当前的设计表单元素是使用对象，但是js的对象遍历是不确定的，如果从后台传表单配置，很可能导致表单显示顺序的不确定性
> 
> 1、因为存在大量的更新和查找操作，如果用数组，每次都需要遍历；
> 2、目前还没遇到过顺序不对的情况，如果你遇到了，可以给我说一下

后台数据序列化json的时候，对象元素的key不一定能安装期望的顺序进行序列化，那么如果form-desc是依赖后台读取的，就无法掌控显示顺序了

**Comment by dream2023** [comment]
> > > 排序问题是存在的，你当前的设计表单元素是使用对象，但是js的对象遍历是不确定的，如果从后台传表单配置，很可能导致表单显示顺序的不确定性
> > 
> > 
> > 1、因为存在大量的更新和查找操作，如果用数组，每次都需要遍历；
> > 2、目前还没遇到过顺序不对的情况，如果你遇到了，可以给我说一下
> 
> 后台数据序列化json的时候，对象元素的key不一定能安装期望的顺序进行序列化，那么如果form-desc是依赖后台读取的，就无法掌控显示顺序了

加这个功能到是不难，但是确实在我用的过程中还没遇到过，你要是遇到过一次，请再次回复这个issue，并附上demo，到时候功能1天内就能上
