### ISSUE TITLE
建议加入栅格布局控件和自定义区域，这样可以设计复杂的布局！

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#16]
参考项目
https://github.com/GavinZhuLei/vue-form-making

**Comment by dream2023** [comment]
有。是在每个表单项上.
![image](https://user-images.githubusercontent.com/19297757/64315698-66c29780-cfe5-11e9-8ffd-d29ee4b61c14.png)

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/64315727-7641e080-cfe5-11e9-863e-0dd7ba20e61d.png)
