### ISSUE TITLE
能否支持Tabs 标签页？把复杂的表单分类分页显示。这个用表单项具名插槽也做不到。

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#17]
能否支持Tabs 标签页？把复杂的表单分类分页显示。
这个用表单项具名插槽也做不到。

**Comment by dream2023** [comment]
可以，也计划支持

**Comment by jackiehe** [comment]
计划什么时候支持？ 现在项目需要，要帮忙请说

**Comment by dream2023** [comment]
我最近会辞职有，估计要一两周，辞职后有时间，你可以先使用tab组件，或者fork下来，进行源码的修改。思路就是讲formDesc改为数组类型

**Comment by jackiehe** [comment]
还有一个表单校验的问题，作为子组件时， 在修改时会失效，调试代码，发现总在校验编辑前的数据。好像不是ele-form的问题，是校验组件不能获取正确的数据。有空时，我写个例子你看看。

**Comment by dream2023** [comment]
> 还有一个表单校验的问题，作为子组件时， 在修改时会失效，调试代码，发现总在校验编辑前的数据。好像不是ele-form的问题，是校验组件不能获取正确的数据。有空时，我写个例子你看看。

好的，最好能有例子，能复现

**Comment by jackiehe** [comment]
你有邮箱吗？我直接工程发给你。

**Comment by dream2023** [comment]
> 你有邮箱吗？我直接工程发给你。

1098626505@qq.com

**Comment by jackiehe** [comment]
代码已经发送，请指导。我用其他方式，组件验证没得问题。

**Comment by dream2023** [comment]
已经解决了，具体请看文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/ue72yy
