### ISSUE TITLE
引入报错SyntaxError: Unexpected token, expected (

### ISSUE THREAD

**Issue by zhenyuan2015** [dream2023/vue-ele-form#19]
![image](https://user-images.githubusercontent.com/12582196/65815704-a2880000-e225-11e9-9229-56edce5ad92e.png)
![image](https://user-images.githubusercontent.com/12582196/65815712-b2074900-e225-11e9-9011-8e41a5f5277a.png)

环境是node 10.16.1
mac下

**Comment by dream2023** [comment]
引入element了吗，element版本和Vue版本？
