### ISSUE TITLE
ele-form-group  联动属性增加建议

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#20]
请将 eleformgroup.vue 改为这样，增加 vif 联动属性， 增加ele-form子组件的ref,去掉ele-form的v-if隐藏，便于提交时验证所有的form.。
`<el-tab-pane
      :key="item.groupId"
      :label="item.groupLabel"
      :name="item.groupId"
      v-for="item of computedGroups"
      v-if="item.vif == null || item.vif(item.form.formData)"
    >
      <ele-form
        :ref="item.groupId"
        v-bind="item.form"
<! ------请删除 v-if="item.groupId === currentGroupId" ---->
        v-on="item.on"
      >`

**Comment by jackiehe** [comment]
<el-tab-pane
      :key="item.groupId"
      :label="item.groupLabel"
      :name="item.groupId"
      v-for="item of computedGroups"
      v-if="item.vif == null || item.vif(item.form.formData)"
    >
      <ele-form
        :ref="item.groupId"
        v-bind="item.form"
        v-if="item.groupId === currentGroupId"
        v-on="item.on"
      >

**Comment by dream2023** [comment]
这个只能自己定制了，无法做到，抱歉
