### ISSUE TITLE
group 分组 能否增加联动属性vif，可以动态隐藏某个tab?

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#23]
## Feature request（新功能建议）
group 分组 能否增加联动属性vif，可以动态隐藏某个tab?
你可以试试在 EleFormGroup.vue 第11行后(el-tab-pane)增加一句
v-if="item.vif == null || item.vif(item.form.formData, item.form.formData[field])"
这样就可以动态隐藏某个tab. 
请看附件示例和修改后的EleFormGroup.vue, 当点击 修改密码 后，会动态显示新旧密码的选项卡。
谢谢了，前面的问题都解决了！ 十分给力！
[ele-form-group-sample.vue.txt](https://github.com/dream2023/vue-ele-form/files/3687269/ele-form-group-sample.vue.txt)
[EleFormGroup.vue.txt](https://github.com/dream2023/vue-ele-form/files/3687270/EleFormGroup.vue.txt)

**Comment by dream2023** [comment]
抱歉，这个尝试了，没能解决，等以后再尝试，最近要处理工作上的事了
