### ISSUE TITLE
group 分组 增加联动属性vif, 只需要增加一句  v-if="item.vif == null || item.vif(item.form.formData, item.form.formData[field])" ，这样的方案不行吗？

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#24]
## Feature request（新功能建议）
 `<el-tab-pane
      :key="item.groupId"
      :label="item.groupLabel"
      :name="item.groupId"
      v-for="item of computedGroups"
      v-if="item.vif == null || item.vif(item.form.formData, item.form.formData[field])"
    >`
[EleFormGroup.vue.txt](https://github.com/dream2023/vue-ele-form/files/3693279/EleFormGroup.vue.txt)

**Comment by dream2023** [comment]
你自己试试，可以的话，可以帮你合进来

**Comment by jackiehe** [comment]
我已经修改好了，用了效果可以，请求你合并下。
代码修改部分
`v-if="item.vif == null || item.vif(item.form.formData, item.form.formData[field])`
完整代码，请看附件文件
[EleFormGroup.vue.txt](https://github.com/dream2023/vue-ele-form/files/3693885/EleFormGroup.vue.txt)

**Comment by dream2023** [comment]
话说，既然能满足你的要求，为什么你自己不能做成自己项目的全局组件呢，重新注册一个名字就可以了，全局注册组件：Vue.component('component-name', component)

**Comment by jackiehe** [comment]
发的贴子是新功能增加建议！我已经在使用，就是每次更新库后，要对比更新下库文件，比较麻烦。单独注册组件，如果你有修改，我这里就会出bug. 也不方便查找问题。 望采纳！

**Comment by dream2023** [comment]
ok

**Comment by dream2023** [comment]
已经添加上了，请下载最新版，不过有一点不同的是，`item.vif(item.form.formData, item.form.formData[field])` 改为了 `item.vif(allFormData)` ，`allFormData` 为所有group里formData的集合
