### ISSUE TITLE
是否是不支持ES6语法？

### ISSUE THREAD

**Issue by wangyuhaoa** [dream2023/vue-ele-form#37]
本地项目使用webpack编译，编译后运行报错
Uncaught SyntaxError: Unexpected identifier
    at Object../node_modules/vue-ele-form/lib/index.js (frame.js:60)
    at t (shared.js:1)
    at Object.eval (eval at 0 (frame.js:1), <anonymous>:42:19)
    at eval (eval at 0 (frame.js:1), <anonymous>:114:30)
    at Object.0 (frame.js:1)
    at t (shared.js:1)
    at window.webpackJsonp (shared.js:1)
    at frame.js:1

**Comment by dream2023** [comment]
支持啊，你是怎么配置的？

**Comment by wangyuhaoa** [comment]
webpack.config.js中
babel: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
    }

**Comment by wangyuhaoa** [comment]
![DF617D97-B0B7-4833-8DCA-FE8541CD9578](https://user-images.githubusercontent.com/28327982/71719570-bf058b00-2e59-11ea-9c24-0296c76aa730.png)

**Comment by dream2023** [comment]
按道理一点问题没有啊, 你要不然新创一个项目, 按照快速指导, 你试试 [https://www.yuque.com/chaojie-vjiel/vbwzgu/xl46cd](https://www.yuque.com/chaojie-vjiel/vbwzgu/xl46cd)

**Comment by dream2023** [comment]
也可以先看一下上面的链接, 看看有没有问题

**Comment by wangyuhaoa** [comment]
我重新试试，是不是我本地webpack版本太低了

**Comment by dream2023** [comment]
> 我重新试试，是不是我本地webpack版本太低了

你用vue-cli3 初始化一个

**Comment by wangyuhaoa** [comment]
vue-cli初始化没问题

**Comment by dream2023** [comment]
> vue-cli初始化没问题

因为现在是采用源码引用的方式, 准备改成编译后的umd引用, 就不会出问题了

**Comment by wangyuhaoa** [comment]
好的

**Comment by dream2023** [comment]
> 好的

已经切换成umd形式了

**Comment by wangyuhaoa** [comment]
好的，我重新试下
