### ISSUE TITLE
新年快乐，如何不展示label

### ISSUE THREAD

**Issue by leubao** [dream2023/vue-ele-form#39]
如何不展示表单label，在动态做搜索框时，一般不需要label,通过提示即可告知作用
#### Other relevant information（格外信息）
- Vue version:
- ElementUI version:2.1.3
- vue-ele-form version:

**Comment by dream2023** [comment]
新年好，需要增加相关特性，今天搞好通知你

**Comment by leubao** [comment]
谢谢

**Comment by dream2023** [comment]
已经ok了，具体请看文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/dyw8a7#Jnr2A
