### ISSUE TITLE
更新到最新后联动属性失效

### ISSUE THREAD

**Issue by xzusoft** [dream2023/vue-ele-form#40]
## Bug report（问题描述）
更新到最新后，联动属性失效 
代码如下
`formDesc: {
        status: {
          options: [
            {
              text: "启用",
              value: 1
            },
            {
              text: "禁用",
              value: -1
            }
          ],
          label: "状态",
          type: "radio",
          attrs: {
            size: "medium"
          },
          default: 1
        },
        password: {
          label: "密码",
          type: "password",
          attrs: {
            size: "medium",
            clearable: true,
          },
          required: true,
          vif (data) {
            return data.status !== 1;
          }
        }
      },`
`<ele-form
        v-model="formData"
        :form-desc="formDesc"
        :form-attrs="{ size: 'small' }"
        :request-fn="handleSubmit"
        @request-success="handleSuccess"
      ></ele-form>`

**Comment by dream2023** [comment]
已修复
