### ISSUE TITLE
单一页面有多个options使用Promise 对象时，会触发多次请求

### ISSUE THREAD

**Issue by xzusoft** [dream2023/vue-ele-form#41]
## Bug report（问题描述）
最新版单一页面有多个options使用Promise 对象时，会触发多次请求
#### Steps to reproduce（问题复现步骤）
`<ele-form-section
        v-model="formData"
        :sections="formDesc"
        :request-fn="handleRequest"
        submitBtnText="下一步"
        :labelPosition="labelPosition"
        :isLoading="isLoading"
        :options-fn="http.get"
        @request-success="handleRequestSuccess"
      >`

`formDesc: {
            headBankCode: {
              options: '/mpc/yeb/bank?is_main=1',
              label: "开户银行编码",
              type: "select",
              required: true,
              attrs:{
                'filterable': true,
                'remote': true,
              }
            },
            bankAddress: {
              default: [],
              options: '/mpc/yeb/region',
              label: "开户行地址",
              type: "cascader",
              required: true
            },
            bankCode: {
              options: '/mpc/yeb/bank',
              label: "开户银行支行编码",
              type: "select",
              required: true
            }
          }`
#### Other relevant information（格外信息）
- Vue version:
- ElementUI version: 2.13
- vue-ele-form version:0.8.22

**Comment by wgbbiao** [comment]
有解决方案不？

**Comment by dream2023** [comment]
已解决，请看文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/rgenav#QWGTm
