### ISSUE TITLE
自有组件中使   用用 ele-form-dialog 组件，加载数据为什么不显示

### ISSUE THREAD

**Issue by bater006** [dream2023/vue-ele-form#45]
自有组件中使   用用 ele-form-dialog 组件，加载数据为什么不显示，当更新一项时，其他数值就都显示了？？
下面是第一种赋值方法：
      const keyArr = Object.keys(this.newColumnValue)
      keyArr.map(item => {
        this.$set(this.formData, item, this.newColumnValue[item])
      })
第二种：Object.assign({},this.formData, this.newColumnValue)
第三种：this.formData = row

以上三种方法都不能更新视图。
当点击增加或修改时，是先显示出来ele-form-dialog 组件，后变化的ele-form-dialog 组件的formData性情？

**Comment by bater006** [comment]
// 增加 会打开对话窗口成 功后执行dialogSuccess，失败执行dialogError
    createRow() {
      // this.formData = this.newColumnValue
      // Object.assign({}, this.formData, this.newColumnValue)
      const keyArr = Object.keys(this.newColumnValue)
      keyArr.map(item => {
        this.$set(this.formData, item, this.newColumnValue[item])
      })
      // this.formData = cloneDeep(this.newColumnValue)
      this.status = 'create'
      this.dialogTitle = '新增'
      this.dialogShow = true
    },

**Comment by dream2023** [comment]
> ```
> // 增加 会打开对话窗口成 功后执行dialogSuccess，失败执行dialogError
> createRow() {
>   // this.formData = this.newColumnValue
>   // Object.assign({}, this.formData, this.newColumnValue)
>   const keyArr = Object.keys(this.newColumnValue)
>   keyArr.map(item => {
>     this.$set(this.formData, item, this.newColumnValue[item])
>   })
>   // this.formData = cloneDeep(this.newColumnValue)
>   this.status = 'create'
>   this.dialogTitle = '新增'
>   this.dialogShow = true
> },
> ```

有  ele-form-dialog 的代码吗
