### ISSUE TITLE
Element UI 2.11集成出现提交表单参数为空

### ISSUE THREAD

**Issue by zddghost** [dream2023/vue-ele-form#47]
#### Other relevant information（格外信息）
- Vue version:
- ElementUI version:2.11

**Comment by zddghost** [comment]
v-model="formObj.formData" 新版本换成这个解决提交无法拿到参数问题

**Comment by dream2023** [comment]
> v-model="formObj.formData" 新版本换成这个解决提交无法拿到参数问题

给一个最小复现 demo
