### ISSUE TITLE
select option为API时，初始化表单会触发表单验证

### ISSUE THREAD

**Issue by HackZZ** [dream2023/vue-ele-form#48]
## Bug report（问题描述）
select option为API时，初始化表单会触发表单验证 

#### Steps to reproduce（问题复现步骤）
 `"formDesc":{
"value":{
"title":{
"label":"取消退费",
"type":"input",
"required":true
},
"test":{
"options":"http://localhost:3000/optionList",
"label":"远程选择器",
"type":"select"
}
}
},`

` <ele-form
         :options-fn="$axios.get"
            :formDesc="formDesc"
            v-model="formData"
            :request-fn="handleRequest"
            @request-success="handleRequestSuccess"
          >
          </ele-form>`

#### Screenshot or Gif（截图或动态图）
![GIF 2020-4-10 17-13-09](https://user-images.githubusercontent.com/19606631/78979738-05504180-7b4f-11ea-9925-21574d522ec5.gif)

#### Other relevant information（格外信息）
- Vue version: 2.5.17
- ElementUI version: 2.12.0
- vue-ele-form version: 0.8.24

**Comment by dream2023** [comment]
已解决 https://www.yuque.com/chaojie-vjiel/vbwzgu/rgenav#QWGTm
