### ISSUE TITLE
请删除EleFormPassword.vue 的 :placeholder="'请输入' + desc.label"，不然调用方无法控制placeholder！

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#5]
<el-input
    :class="desc.class"
    :placeholder="'请输入' + desc.label"
    :show-password="true"
    :style="desc.style"
    v-bind="attrs"
    v-model="newValue"
    v-on="onEvents"
  >

如果不删除
我在外面调用时，无法用 attrs 修改它
          attrs : {
            "placeholder":this.$t('message.inputpassword')
          }

如果不删除， 请改为 
:placeholder="desc.placeholder"
我也可以在外部控制它
formDesc: {"password":{"type":"password","label":this.$t('message.password'),"default":"","placeholder":this.$t('message.inputpassword')}

两种方法都可以

**Comment by dream2023** [comment]
OK，我考虑一下，还有其他组件也有类似的，我统一处理一下

**Comment by jackiehe** [comment]
嗯，我已经先自行删除了。

**Comment by dream2023** [comment]
已经修复了
