### ISSUE TITLE
是否支持根据接口返回字段生成表单

### ISSUE THREAD

**Issue by baggiomygod** [dream2023/vue-ele-form#50]
## Question（提问）
您好，我用这个ele-form.希望是根据接口返回，然后动态生成formDesc, 

#### Steps to reproduce（问题复现步骤）
当从接口获取字段，然后生成forDesc时回报错：
Error in getter for watcher "computedFormDesc": "TypeError: Cannot create property '_vifs' on number '200'"

```
created() {
    this.getFormDesc()
  },
  methods: {
    async getFormDesc() {
      const form = await getFormDesc()
      this.formDesc = JSON.parse(JSON.stringify(form))
    },
}
```

请问有实现异步创建的方法吗？
#### Other relevant information（格外信息）
- Vue version: 2.
- ElementUI version:2.13.0
- vue-ele-form version:0.8.24

**Comment by dream2023** [comment]
你看看自己的返回值
