### ISSUE TITLE
表单载入默认数据

### ISSUE THREAD

**Issue by xu4wang** [dream2023/vue-ele-form#51]
请问下，可以给表单载入默认数据吗？ 

例如在最初展示表单时候，对于每一个text，selection等，都从服务器获取的json文件中初始化成默认值，然后用户可以在这个基础上编辑。

谢谢。

**Comment by wangmeng1991** [comment]
formData: {key:value}

**Comment by dream2023** [comment]
看文档，https://www.yuque.com/chaojie-vjiel/vbwzgu/dyw8a7#b2AbF

**Comment by BlibliBoom** [comment]
但是图片的赋值不行，image : 'http://xxxx' 失败
