### ISSUE TITLE
dialog模式下必填验证bug

### ISSUE THREAD

**Issue by wangmeng1991** [dream2023/vue-ele-form#52]
## Bug report（问题描述）
dialog模式下change时验证上次内容
#### Steps to reproduce（问题复现步骤）
` <ele-form-dialog
      v-model="formData"
      :visible="true"
      :formDesc="formDesc"
    />`
`  formData: {},`
`
        formDesc: {
          username: {
            label: "用户名称",
            type: "input",
            required: true,
            layout: 12,
          }, }`

#### Screenshot or Gif（截图或动态图）
https://s1.ax1x.com/2020/05/08/YumpBF.gif

#### Other relevant information（格外信息）
- Vue version: 2.6.11
- ElementUI version: 2.13.1
- vue-ele-form version: 0.8.24

**Comment by dream2023** [comment]
已解决
