### ISSUE TITLE
表单页载入完成后必填项错误直接显示

### ISSUE THREAD

**Issue by xzusoft** [dream2023/vue-ele-form#54]
## Bug report（问题描述）
1、表单页载入完成后必填项错误直接显示
2、select组件完成选择后，必填错误提示并不消失，但表单可以正常提交
#### Other relevant information（格外信息）
- Vue version:
- ElementUI version: 最新版
- vue-ele-form version: 最新版

**Comment by dream2023** [comment]
已解决
