### ISSUE TITLE
image-uploader 组件报错

### ISSUE THREAD

**Issue by osm-tech** [dream2023/vue-ele-form#57]
## Bug report（问题描述）
按照以下配置进行配置之后报错，图片是能够正常上传的

```
        logo: {
          label: "上传图标",
          required: true,
          type: "image-uploader",
          attrs: {
            drag: true,
            fileType: [],
            action: "http://localhost:3000/api/file/upload",
            data: {
              token:""
            }
          }
        }
```
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/66452398/84624165-73303500-af13-11ea-8d12-935d6adaf39b.png)

**Comment by osm-tech** [comment]
vue-ele-upload-image 中 value （value看起来像是后端返回的数据）错误的为Object了导致无法被 spread，可以使用responseFn回调来绕过这个错误。
在 vue-ele-upload-image文档中value的可选类型和源码不符

**Comment by dream2023** [comment]
https://github.com/dream2023/vue-ele-upload-image#%E7%A4%BA%E4%BE%8B

请按照文档返回字符串（单个）或者数组（多个）
