### ISSUE TITLE
请修改EleForm.vue的:label-position="formLabelPosition"为"labelPosition"！不然"labelPosition"不起作用，和你的说明不相符

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#6]
EleForm.vue:
        <el-form
          :label-position="labelPosition"
          :label-width="labelWidth + 'px'"
          :model="formData"
          :rules="rules"
          @submit.native.prevent="handleValidateForm"
          ref="form"
        >

调用方法
        <ele-form
                :isShowBackBtn="false"
                :submitBtnText="$t('message.login')"
                labelPosition="left"
                :labelWidth="0"
                :rules="rules"
                :form-desc="formDesc"
                :form-data="formData"
                :request-fn="handleRequest"
                @request-success="handleRequestSuccess"
        ></ele-form>

**Comment by dream2023** [comment]
```html
<el-form
:label-position="labelPosition"
:label-width="labelWidth + 'px'"
:model="formData"
:rules="rules"
@submit.native.prevent="handleValidateForm"
ref="form"
/>
```

这里的`labelPosition`的是变量，取值为`left`, `right`, `top`

**Comment by jackiehe** [comment]
嗯，我知道。但是你的源代码里是  :label-position="formLabelPosition"
不过好像不影响使用。+

**Comment by dream2023** [comment]
> 嗯，我知道。但是你的源代码里是 :label-position="formLabelPosition"
> 不过好像不影响使用。+

源码里因为有响应式处理，所以在不传值时，会进行判断，所以用的变量
