### ISSUE TITLE
请问怎么关掉 对json数据的自动排序功能

### ISSUE THREAD

**Issue by Annfyl** [dream2023/vue-ele-form#60]
#### 原因
- 我录入数据后存到后台，然后在从后台拿出来的时候顺序就变了，因为进行了自动排序
希望我能关掉这个自动排序，或者让这个功能变成可控的

**Comment by dream2023** [comment]
因为数据结构目前是对象的，排序不收控制，不过我还没遇到过乱的情况，能否提供一下

**Comment by z5980000** [comment]
对象遍历在不同浏览器上是不同的，有可能你保存的时候跟拿出来的时候是用的不同浏览器，所以导致对象遍历不同。这里是否可以考虑提供一个order的配置项来指定表单项的顺序？

**Comment by dream2023** [comment]
> order

可以的

**Comment by dream2023** [comment]
> 对象遍历在不同浏览器上是不同的，有可能你保存的时候跟拿出来的时候是用的不同浏览器，所以导致对象遍历不同。这里是否可以考虑提供一个order的配置项来指定表单项的顺序？

我想了想，目前的数据结构还是不太适合，我正在做另一个类似的组件，到时候它采用的是数组，不会出现这个问题了

**Comment by z5980000** [comment]
> > 对象遍历在不同浏览器上是不同的，有可能你保存的时候跟拿出来的时候是用的不同浏览器，所以导致对象遍历不同。这里是否可以考虑提供一个order的配置项来指定表单项的顺序？
> 
> 我想了想，目前的数据结构还是不太适合，我正在做另一个类似的组件，到时候它采用的是数组，不会出现这个问题了

另一个类似的组件是指什么？我想实现这个功能，会跟你这边做的有冲突吗？
