### ISSUE TITLE
关于图片上传组件node后台接收数据问题

### ISSUE THREAD

**Issue by gaoqiang1991a** [dream2023/vue-ele-form#7]
你好大佬，请问下这里面的图片和视频等文件上传组件，是否支持使用node-express框架构建的服务端后台用formidable.js模块实现上传的图片或视频等文件数据的解析？也即图片上传组件是否是通过二进制数据格式向后台发送的数据？

**Comment by dream2023** [comment]
没用过，我晚上查查
