### ISSUE TITLE
自定义组件间传递参数信息只能借用options，但是options 的修改会导致val 的值被清空。

### ISSUE THREAD

**Issue by liangwenle** [dream2023/vue-ele-form#73]
一般来说用到自定义组件其需要实现的功能相对比较复杂，有这么一个场景
字段A：多选择框，
字段B： 
             1. 自定义组件： 一个输入框；按钮类型1 两个 and、 or；按钮类型2 多个，来源于A字段选择；
             2. 目的：字段A 选择了以后，把选择的值实时同步到按钮类型2，再通过按钮类型1 和按钮类型2 的点击来排列组合为字段B 的值。 eg： [字段A.p1]  [and]  [字段A.p2]  [or]  [字段A.p3] 

问题1：字段A 选择的值只能通过options 传递给字段B，而form 有一个判断如果当options 改变了把字段B 的值清空了，这个不是期望的结果
解决：
        方案1.多加一个只是用来传递参数的配置项
        方案2.或者把options 修改后是否清空val的控制开放出来。
推荐第一个解决方案。

问题二： 由于用了options 当做传递参数。 导致本来options 的功能没法用，比如我刚好还需要用到options 做异步数据请求等。

**Comment by dream2023** [comment]
会将formData传入每个组件内，这样就可以操作其它数据了

**Comment by liangwenle** [comment]
也可以，但是要把字段A被修改的事件也一起通知到字段B，这样才能实时改变字段B 的内容

**Comment by dream2023** [comment]
已修复，请更新。
如果直接修改formData，联动检测将不会其作用，可以通过 `this.$parent.setValue(field, value)` 进行更改
