### ISSUE TITLE
自定义组件和规则配合使用时，规则错误提示只能再组件最下面。感觉体验比较奇怪

### ISSUE THREAD

**Issue by liangwenle** [dream2023/vue-ele-form#74]
一般来说自定义组件是为了实现比复杂的功能，用到的控件比较多，可能有input，多个按钮还可以加上tree list 的选择。

这么多的控件组合到一起导致比较高的高度，但是规则检验失败的红色提示只会再整个自定义组件最下面。导致体验不好，提示位置不到位。

建议：把红色的提醒信息 开放给自定义组件中，由自定义组件的代码选择提示位置。如果可以提示的红色框也可以开放出来

**Comment by dream2023** [comment]
鉴于当前架构问题，暂不调整
