### ISSUE TITLE
手动赋值的字段验证有问题

### ISSUE THREAD

**Issue by akhuting** [dream2023/vue-ele-form#77]
#### Steps to reproduce（问题复现步骤）
1. 动态加载select options
2. 默认选中第一项(手动赋值)
3. 必填验证不通过,就算再次重新选择其他option也不会通过,但是操作一下其他控件再回来选择验证通过

#### Screenshot or Gif（截图或动态图）

![2020-08-18 10 42 15](https://user-images.githubusercontent.com/1799250/90464772-9f994500-e140-11ea-8a59-6c3109a051e5.gif)

**Comment by dream2023** [comment]
主要是没有触发响应，
```js
// 单个赋值，可以通过 `$set` 触发响应
this.$set(this.formData, 'student', 1)
```
或者

```js
this.formData = { student: 1 }
```

**Comment by dream2023** [comment]
具体看文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/dyw8a7#b2AbF
