### ISSUE TITLE
可否支持多文件上传

### ISSUE THREAD

**Issue by wuwujay** [dream2023/vue-ele-form#8]
希望增加一个多文件上传组件

**Comment by dream2023** [comment]
会的，如果你是上传图片和视频，可以推荐这两个组件：https://www.yuque.com/chaojie-vjiel/vbwzgu/sv990y，https://www.yuque.com/chaojie-vjiel/vbwzgu/gbdhup

**Comment by dream2023** [comment]
已经有了，请看文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/cqtrgb
