### ISSUE TITLE
移动端表单

### ISSUE THREAD

**Issue by z5980000** [dream2023/vue-ele-form#80]
## Feature request（新功能建议）

有考虑要做 移动端的表单吗？

**Comment by dream2023** [comment]
具体的应用场景能举一个例子吗，如果用处过少，可能不会做，如果用处多的话倒是可以

**Comment by z5980000** [comment]
就是想要做一些支持移动h5的表单组件，目前vue-ele-form的表单组件都是针对pc端的，如果我想加入一些移动端的表单组件，会不会与你最初的设计初衷违背？

**Comment by dream2023** [comment]
只要能显示的比较好，你自定义组件就好
