### ISSUE TITLE
表单按钮支持disabled属性

### ISSUE THREAD

**Issue by agzou** [dream2023/vue-ele-form#82]
## Feature request（新功能建议）
基于一些业务场景，比如一个表单，某些属性没有填或者不满足某些规则，这个时候不能让用户点击查询或者提交按钮，应该把按钮禁用，可以把按钮原本的disabled属性暴露出来。

**Comment by dream2023** [comment]
已经提供了显示隐藏，我个人感觉就足够了吧，https://www.yuque.com/chaojie-vjiel/vbwzgu/dyw8a7#vsMDo

**Comment by dream2023** [comment]
或者你用自定义按钮 https://www.yuque.com/chaojie-vjiel/vbwzgu/dyw8a7#toLl5
或者用插槽：https://www.yuque.com/chaojie-vjiel/vbwzgu/cmerhn#dMu6Y

**Comment by agzou** [comment]
自定义按钮或者插槽也是可以的，只是要自己多处理一次submit
