### ISSUE TITLE
props.formDesc监听不到序列改变

### ISSUE THREAD

**Issue by JayTam** [dream2023/vue-ele-form#85]
#### 问题
formDesc内容不变，但是formDesc的引用发生改变（顺序改变，如下），ele-form的formDesc无法监听到改变，不会重新渲染。该问题会导致f-render拖动功能无法使用。
```js
formDesc = { title: {}, content: {} }
formDesc = { content: {}, title: {} }
```

#### 期望
只要formDesc的引用发生改变，ele-form就应该能监听到变化，并重新渲染一遍。
#### 版本
ele-form：0.8.43
0.8.42 没有问题，就是0.8.43改出了问题 
#### Steps to reproduce（问题复现步骤）

1. 点击下面codesandbox链接
2. 等待依赖安装完成，出现表单页面
3. 点击最下面的测试按钮

可以看到打印出来的formDesc，*内容表单项*和*标题表单项*的顺序交换了，但在ele-form中没有交换
  

#### Link to minimal reproduction（最小可在线还原demo）

https://codesandbox.io/s/fast-pine-10imb?file=/src/main.js

**Comment by dream2023** [comment]
目前拖拽功能正常，你的PR，不能那样改，会导致其它问题

**Comment by dream2023** [comment]
如果是老版本，建议升级，不升级总是会有问题
