### ISSUE TITLE
这里是不是会污染全局样式

### ISSUE THREAD

**Issue by janlycn** [dream2023/vue-ele-form#88]
## Bug report（问题描述）
引入之后发现有些地方日期控件宽度变成了100%

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/39581938/94335667-a3599a80-000f-11eb-80f0-9f0e7615eb79.png)

#### Other relevant information（格外信息）
- Vue version: 2.5.13
- ElementUI version: 2.13.0
- vue-ele-form version: 0.8.44

**Comment by dream2023** [comment]
已解决
