### ISSUE TITLE
如何使用trim修饰符

### ISSUE THREAD

**Issue by akhuting** [dream2023/vue-ele-form#89]
如何使用trim修饰符来实现去空格的功能,或者有其他类似的方法来实现吗?

**Comment by dream2023** [comment]
没法使用trim

可以使用这两个代替：

https://www.yuque.com/chaojie-vjiel/vbwzgu/iw5dzf#qPV8C

https://www.yuque.com/chaojie-vjiel/vbwzgu/iw5dzf#4fzKL
